[workspace]
members = ["qwen_tts", "qwen_tts_cli"]
resolver = "3"

[workspace.package]
version = "0.1.1"
edition = "2024"
repository = "https://github.com/danielclough/qwen3-tts-rs"
license = "MIT OR Apache-2.0"