[workspace]
members = ["qwen3_tts", "qwen3_tts_cli"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/danielclough/qwen3-tts"
license = "MIT OR Apache-2.0"